# Название исходного файла
SOURCE_NAME = 'main.c'

# Рабочая директория, т.е. директория, в которой находится наша программа
WORKING_DIRECTORY = '..'

# Папка, в которую будут помещаться все системные файлы
SERVICE_DIRECTORY_NAME = 'data'

# Количества запусков
RUNS = [10, 100, 1000, 10000]

# Количества элементов массива для каждого из запусков
POINTS = [10, 20, 50, 100, 200, 400, 800, 1600, 3200, 6400, 12800]

# Минимальное и максимальное значение
MIN = 0
MAX = 10000

# Ключи компиляции
GCC_KEYS = ['-Wall', '-Wpedantic', '-Wextra', '-Wall', '-Wvla']