@startuml
"Предлагаемое решение" -> Kubernetes: Запрос информации об объекте,\nописывающем том
Kubernetes --> "Предлагаемое решение": Подробная информация об объекте,\nописывающем том

"Предлагаемое решение" -> Kubernetes: Запрос уникального идентификатора тома
Kubernetes --> "Предлагаемое решение": Уникальный идентификатор тома

"Предлагаемое решение" -> "Container Runtime Interface": Запрос системной информации о контейнере
"Container Runtime Interface" --> "Предлагаемое решение": Системная информация о контейнере

"Предлагаемое решение" -> "Предлагаемое решение": Получение идентификатора основного\nпроцесса контейнера

"Предлагаемое решение" -> "Файловая система /proc": Чтение файла с информацией\nо точках монтирования процесса
"Файловая система /proc" --> "Предлагаемое решение": Содержимое файла с информацией\nо точках монтирования процесса

"Предлагаемое решение" -> "Предлагаемое решение": Формирование записи с полученной информацией
@enduml