package generator

type Product struct {
	ID               int     `csv:"id"`
	Name             string  `csv:"name"`
	Description      string  `csv:"description"`
	MinSafetyClassID int     `csv:"min_safety_class"`
	ItemName         string  `csv:"item_name"`
	Price            float64 `csv:"price"`
	Slug             string  `csv:"slug"`
	CategoryID       int     `csv:"category_id"`
}

func genProducts() ([]Product, error) {
	return []Product{
		{
			ID:               1,
			Name:             "Чистый амфетамин",
			Description:      "Представляет собой однородный порошок белого или кремового цвета со специфическим запахом. Считается наиболее качественным видом наркотика.",
			MinSafetyClassID: 3,
			ItemName:         "1 грамм",
			Price:            5000,
			Slug:             "pure_amphetamine",
			CategoryID:       7,
		},
		{
			ID:               2,
			Name:             "Амфетамин в таблетках",
			Description:      "Прием стимулятора в таблетированной форме пользуется среди наркозависимых большой популярностью.",
			MinSafetyClassID: 2,
			ItemName:         "5 таблеток",
			Price:            3000,
			Slug:             "amphetamine_in_tablets",
			CategoryID:       7,
		},
		{
			ID:               3,
			Name:             "Мокрый фен",
			Description:      "Жидкая форма представляет собой концентрат психоактивного вещества.",
			MinSafetyClassID: 4,
			ItemName:         "1 ампула (2 грамма)",
			Price:            13000,
			Slug:             "liquid_amphetamine",
			CategoryID:       7,
		},
		{
			ID:               4,
			Name:             "Таблетки экстази",
			Description:      "Экстази также называют XTC, чупа-чупс, Манди, Molly и т.д. Яркие таблетки принимаются энтерально и дают эффект уже через 30-40 минут.",
			MinSafetyClassID: 1,
			ItemName:         "10 таблеток",
			Price:            15000,
			Slug:             "ecstasy_pills",
			CategoryID:       10,
		},
		{
			ID:               5,
			Name:             "Тесла",
			Description:      "Тесла представляет собой подвид экстази, чаще всего имеющий оранжевый оттенок. Это таблетки, включающие в себя 240 грамм активного вещества, т.е. практически летальную дозу. Данный вид наркотического вещества чаще всего выпускают в ночных клубах.",
			MinSafetyClassID: 3,
			ItemName:         "1 таблетка",
			Price:            2000,
			Slug:             "tesla",
			CategoryID:       10,
		},
		{
			ID:               6,
			Name:             "МДМА",
			Description:      "МДМА представляет собой вещество, которое использовалось в медицине в качестве коагулянта. Несмотря на кровоостанавливающие свойства, по прямому назначению оно не применялось: о МДМА вспомнили только через несколько десятков лет из-за схожести с мескалином.",
			MinSafetyClassID: 2,
			ItemName:         "5 таблеток",
			Price:            4000,
			Slug:             "mdma",
			CategoryID:       10,
		},
		{
			ID:               7,
			Name:             "Ешка",
			Description:      "Ешка представляет собой экстази на сленге молодежи. Данный наркотик обладает сильным эффектом и часто встречается на концертах, рейв-тусовках, в клубах и т.д. ",
			MinSafetyClassID: 1,
			ItemName:         "15 таблеток",
			Price:            5000,
			Slug:             "e",
			CategoryID:       10,
		},
		{
			ID:               8,
			Name:             "Мелатонин",
			Description:      "Препарат от нарушения сна",
			MinSafetyClassID: 1,
			ItemName:         "1 упаковка (100 таблеток)",
			Price:            800,
			Slug:             "melatonin",
			CategoryID:       11,
		},
		{
			ID:               9,
			Name:             "Героин (Афганистан)",
			Description:      "Отборный героин с низовий афганской деревни.",
			MinSafetyClassID: 5,
			ItemName:         "10 мг",
			Price:            5000,
			Slug:             "heroine-afganistan",
			CategoryID:       12,
		},
		{
			ID:               10,
			Name:             "Героин (Куба)",
			Description:      "Отборный героин с низовий кубинских плантаций.",
			MinSafetyClassID: 6,
			ItemName:         "10 мг",
			Price:            6500,
			Slug:             "heroine-cuba",
			CategoryID:       12,
		},
		{
			ID:               11,
			Name:             "Героин (Украина)",
			Description:      "Отборный героин с украинских свиноферм.",
			MinSafetyClassID: 5,
			ItemName:         "15 мг",
			Price:            4000,
			Slug:             "heroine-ua",
			CategoryID:       12,
		},
		{
			ID:               12,
			Name:             "Опий-сырец (Афганистан)",
			Description:      "Субстанцию можно использовать для своего творчества.",
			MinSafetyClassID: 6,
			ItemName:         "50 грамм",
			Price:            100000,
			Slug:             "opium-raw",
			CategoryID:       13,
		},
		{
			ID:               13,
			Name:             "Амидон",
			Description:      "Описание товара...",
			MinSafetyClassID: 3,
			ItemName:         "10 таблеток",
			Price:            10000,
			Slug:             "amidon",
			CategoryID:       14,
		},
		{
			ID:               14,
			Name:             "Дольфин",
			Description:      "Описание товара...",
			MinSafetyClassID: 3,
			ItemName:         "15 таблеток",
			Price:            20000,
			Slug:             "dolfin",
			CategoryID:       14,
		},
		{
			ID:               15,
			Name:             "Метадон",
			Description:      "Метадон применяется в ряде стран в заместительной терапии употребления «тяжёлых» наркотиков как заместитель героина («метадоновая программа»).",
			MinSafetyClassID: 4,
			ItemName:         "10 таблеток",
			Price:            20000,
			Slug:             "matadounium",
			CategoryID:       14,
		},
		{
			ID:               16,
			Name:             "Конопля посевная",
			Description:      "Тут все понятно.",
			MinSafetyClassID: 2,
			ItemName:         "1 грамм",
			Price:            2000,
			Slug:             "cannabis_posev",
			CategoryID:       15,
		},
		{
			ID:               17,
			Name:             "Конопля индийская",
			Description:      "Лучший сорт Индии.",
			MinSafetyClassID: 2,
			ItemName:         "1 грамм",
			Price:            3000,
			Slug:             "cannabis_india",
			CategoryID:       15,
		},
		{
			ID:               18,
			Name:             "Конопля сорная",
			Description:      "Конопля сорная — подвид конопли посевной, впервые описанный в 1924 году Дмитрием Янишевским как самостоятельный вид. Растение рудеральное, невысокое (до 60 см), редко ветвящееся, с небольшими тонкими листьями и тонким центральным стеблем. В благоприятных условиях растения могут достигать высоты 3 метра. По внешнему виду может быть похожа на культурную коноплю, являясь её специализированным сорняком. Созревает очень быстро (иногда к середине июля, при хорошем поливе).",
			MinSafetyClassID: 2,
			ItemName:         "1 грамм",
			Price:            1500,
			Slug:             "cannabis-sorn",
			CategoryID:       15,
		},
		{
			ID:               19,
			Name:             "Конопля высушенная",
			Description:      "Для сладкого курева.",
			MinSafetyClassID: 3,
			ItemName:         "1 грамм",
			Price:            4000,
			Slug:             "cannabis-dry",
			CategoryID:       15,
		},
		{
			ID:               20,
			Name:             "Конопля (семена)",
			Description:      "Для своих плантаций.",
			MinSafetyClassID: 3,
			ItemName:         "1 грамм",
			Price:            4000,
			Slug:             "cannabis-semen",
			CategoryID:       15,
		},
		{
			ID:               21,
			Name:             "Гашиш (Афганистан)",
			Description:      "Топовый гашиш из верховий афганских гор.",
			MinSafetyClassID: 3,
			ItemName:         "1 грамм",
			Price:            2000,
			Slug:             "hashish-afgan",
			CategoryID:       16,
		},
		{
			ID:               22,
			Name:             "Гашиш (Россия)",
			Description:      "Описание товара...",
			MinSafetyClassID: 3,
			ItemName:         "1 грамм",
			Price:            1000,
			Slug:             "hashish-russia",
			CategoryID:       16,
		},
		{
			ID:               23,
			Name:             "Кокаин (Куба)",
			Description:      "Сладкий кокаин с негритянских плантаций Кубы.",
			MinSafetyClassID: 5,
			ItemName:         "1 грамм",
			Price:            12000,
			Slug:             "cocaine-cuba",
			CategoryID:       17,
		},
		{
			ID:               24,
			Name:             "Кокаин (Голландия)",
			Description:      "Европейское качество.",
			MinSafetyClassID: 5,
			ItemName:         "1 грамм",
			Price:            20000,
			Slug:             "cocaine-holland",
			CategoryID:       17,
		},
		{
			ID:               25,
			Name:             "Крек (Мексика)",
			Description:      "Самый лучший мексиканский крек на рынке.",
			MinSafetyClassID: 5,
			ItemName:         "1 грамм",
			Price:            10000,
			Slug:             "crack-mexico",
			CategoryID:       18,
		},
		{
			ID:               26,
			Name:             "Крек (США)",
			Description:      "Самый лучший американский крек на рынке.",
			MinSafetyClassID: 5,
			ItemName:         "1 грамм",
			Price:            13000,
			Slug:             "crack-usa",
			CategoryID:       18,
		},
		{
			ID:               27,
			Name:             "Крек (Пакистан)",
			Description:      "Описание товара...",
			MinSafetyClassID: 5,
			ItemName:         "1 грамм",
			Price:            8000,
			Slug:             "crack-pakistan",
			CategoryID:       18,
		},
		{
			ID:               28,
			Name:             "Крек (как у американских реперов)",
			Description:      "Любишь американских нигга-реп про крек, текилу и чилл? Тогда ты по адресу! Лучший крек, как у XXXTenrationa и Фараона.",
			MinSafetyClassID: 5,
			ItemName:         "1 грамм",
			Price:            20000,
			Slug:             "crack-rap",
			CategoryID:       18,
		},
		{
			ID:               29,
			Name:             "ЛСД (Россия)",
			Description:      "Описание товара...",
			MinSafetyClassID: 4,
			ItemName:         "1 ампула (1.5 грамма)",
			Price:            4000,
			Slug:             "lsd-russia",
			CategoryID:       19,
		},
		{
			ID:               30,
			Name:             "Мухомор (сушеный)",
			Description:      "Сушеные мухоморы из глубоких лесов России.",
			MinSafetyClassID: 3,
			ItemName:         "1 грамм",
			Price:            1000,
			Slug:             "muhomors",
			CategoryID:       20,
		},
		{
			ID:               31,
			Name:             "Белая поганка (сушеная)",
			Description:      "Описание товара...",
			MinSafetyClassID: 3,
			ItemName:         "1 грамм",
			Price:            900,
			Slug:             "white-pogan",
			CategoryID:       20,
		},
		{
			ID:               32,
			Name:             "Бледная поганка (сушеная)",
			Description:      "Внимание! Опасно! Перед употреблением ознакомиться с инструкцией!",
			MinSafetyClassID: 4,
			ItemName:         "25 мг",
			Price:            3000,
			Slug:             "bled-pogan",
			CategoryID:       20,
		},
		{
			ID:               33,
			Name:             "Нож Чекиста (Нож Победы с шкатулкой)",
			Description:      "Длина клинка (мм) — 125.\nШирина клинка (мм) — 22.",
			MinSafetyClassID: 1,
			ItemName:         "1 шт",
			Price:            16000,
			Slug:             "nozh-chekista-nozh-pobedy-s-shkatulkoy",
			CategoryID:       21,
		},
		{
			ID:               34,
			Name:             "Нож Хищник D2 мельхиор Кизляр",
			Description:      "Длина клинка (мм) — 145.\nШирина клинка (мм) — 29.",
			MinSafetyClassID: 1,
			ItemName:         "1 шт",
			Price:            5992,
			Slug:             "nozh-khishchnik-d2-melkhior-kizlyar",
			CategoryID:       21,
		},
		{
			ID:               35,
			Name:             "Нож Орел граб/дамаск ИП Эмиров Кизляр",
			Description:      "Общая длина (мм): 275-315.\nДлина клинка (мм): 150-180.",
			MinSafetyClassID: 1,
			ItemName:         "1 шт",
			Price:            4983,
			Slug:             "nozh-orel-grab-damask-ip-emirov-kizlyar",
			CategoryID:       21,
		},
		{
			ID:               36,
			Name:             "Мачете Yeti Black – Mr. Blade",
			Description:      "Общая длина (мм) — 444.\nДлина клинка (мм) — 292.",
			MinSafetyClassID: 1,
			ItemName:         "1 шт",
			Price:            10615,
			Slug:             "machete-yeti-black-mr-blade",
			CategoryID:       21,
		},
		{
			ID:               37,
			Name:             "Нож Sting - G10 black s/w N.C.Custom",
			Description:      "Общая длина (мм) — 275.\nДлина клинка (мм) — 149.",
			MinSafetyClassID: 1,
			ItemName:         "1 шт",
			Price:            10490,
			Slug:             "nozh-sting-g10-black-s-w-n-c-custom",
			CategoryID:       21,
		},
		{
			ID:               38,
			Name:             "Нож Боярин (кожа)",
			Description:      "Настоящий мужской нож «Боярин» из коррозийно-стойкой стали 50*14 мф выгодно отличается от аналогичных своими физическими параметрами. При 425 мм общего размера, параметры самого клинка имеют 288 мм длины и 28 мм ширины. Толщина клинка 6мм и особая конфигурация стального полотна позволяет назвать его не просто туристическим ножом, а и мачете. Рукоять изделия облачена в кожу, но имеет алюминиевые навершие и гарду. Кожаные ножны надежно сохранят нож от внешних воздействий и предотвратят возможность пораниться при хранении и транспортировке. ГОСТ 1 52737-2007 причисляет этот клинок к категории охотничьих тесаков и разделочных инструментов, а это значит, что купить Боярин Златоуст можно в свободной продаже. Он не считается холодным оружием.",
			MinSafetyClassID: 1,
			ItemName:         "1 шт",
			Price:            5265,
			Slug:             "nozh-boyarin-kozha",
			CategoryID:       21,
		},
		{
			ID:               45,
			Name:             "Smith&Wesson Military&Police",
			Description:      "Пистолет имеет камеру с калибрами .40 S&W, .375 SIG, .45 ACP и 9x19 мм. Парабеллум. Версия .40 S&W в основном используется в правоохранительных целях, а 9x19 мм – для военного использования.",
			MinSafetyClassID: 5,
			ItemName:         "1 шт",
			Price:            29_386,
			Slug:             "smith-wesson-military-police",
			CategoryID:       26,
		},
		{
			ID:               46,
			Name:             "Beretta 92",
			Description:      "Beretta 92 адаптирована к патронам размером 9x19 мм Парабеллум. Он имеет короткую отдачу. Он более мощный, чем более ранние итальянские пистолеты, которые имеют эффект продувки. Также Beretta 92 является точной, даже на большом расстоянии. Также некоторые люди находят дизайн этого пистолета элегантным.",
			MinSafetyClassID: 5,
			ItemName:         "1 шт",
			Price:            39_238,
			Slug:             "beretta-42",
			CategoryID:       26,
		},
		{
			ID:               47,
			Name:             "Glock 17",
			Description:      "Пистолет имеет простую конструкцию с минимальным количеством деталей. Есть только 33 детали, включая магазин. Этот пистолет можно разобрать в течение минуты, используя только штифт или гвоздь. Многие детали взаимозаменяемы между различными моделями Glock. Glock 17 также прост в эксплуатации.",
			MinSafetyClassID: 5,
			ItemName:         "1 шт",
			Price:            50_134,
			Slug:             "glock-17",
			CategoryID:       26,
		},
		{
			ID:               48,
			Name:             "Пистолет Макарова",
			Description:      "Действие автоматики ПМ основано на свободном затворе. Запирание ствола происходит за счёт инертной массы затвора. Упругость возвратной пружины, надетой на ствол, в самом запирании не участвует, она всего лишь возвращает затвор в переднее положение. Ударно-спусковой механизм двойного действия с открытым курком. В ПМ применён свободный ударник, не имеющий пружины, удерживающей его в заднем положении. Теоретически это может привести к самопроизвольному выстрелу при падении пистолета с большой высоты, но Н. Ф. Макаров считал, что ударник не обладает достаточной массой, чтобы всерьёз учитывать эту возможность.",
			MinSafetyClassID: 5,
			ItemName:         "1 шт",
			Price:            16_249,
			Slug:             "makarich",
			CategoryID:       26,
		},
		{
			ID:               49,
			Name:             "Pecheneg",
			Description:      "Единый пулемет «Печенег» предназначается для поражения живой силы врага и легкой техники. Его также можно использовать как зенитное орудие. Благодаря своим характеристикам он по праву считается одним из лучших образцов единых пулеметов в мире.",
			MinSafetyClassID: 6,
			ItemName:         "1 шт",
			Price:            192_248,
			Slug:             "pecheneg",
			CategoryID:       27,
		},
		{
			ID:               50,
			Name:             "FN MAG",
			Description:      "FN MAG полноправно можно назвать «бельгийской лошадкой» в классе стрелкового вооружения. Оружейники из Fabrique Nationale постарались на славу, создав поистине хороший пулемёт. Достаточно простая и надежная конструкция в сочетании с гибкостью применения и адекватным боеприпасом обеспечили этому пулемету место в системе вооружений свыше чем 50 стран мира, включая саму Бельгию, Великобританию, Австралию, Канаду, США, Швецию и многие другие страны.",
			MinSafetyClassID: 6,
			ItemName:         "1 шт",
			Price:            210_293,
			Slug:             "fn-mag",
			CategoryID:       27,
		},
		{
			ID:               51,
			Name:             "DongFeng 31 (DF-31A)",
			Description:      "DongFeng 31A или DF-31A (название по классификации НАТО: CSS-9 Mod-2) - китайская межконтинентальная баллистическая ракета с дальностью 11 200 километров.",
			MinSafetyClassID: 7,
			ItemName:         "1 шт",
			Price:            0,
			Slug:             "dong-feng",
			CategoryID:       28,
		},
		{
			ID:               52,
			Name:             "Т-90АМ",
			Description:      "В период холодной войны, СССР проводила активную политику в военной сфере, что обусловило производство относительно дешевой и дорогой версии танков. В последнее время основные мощности были сосредоточены на изготовлении Т-90АМ с различными модификациями, экспортируемыми в другие государства. Конструкция аналогична с Т-72, однако дополнена пушкой 125 мм, двигателем мощностью 1230 л.с и повышенной защитой. Цена варьируется от 4,25 до 4,5 млн долларов.",
			MinSafetyClassID: 7,
			ItemName:         "1 ед",
			Price:            276_382_384,
			Slug:             "t-90am",
			CategoryID:       30,
		},
		{
			ID:               53,
			Name:             "Pu-239",
			Description:      "Плутоний.",
			MinSafetyClassID: 7,
			ItemName:         "50 грамм",
			Price:            36_642_000,
			Slug:             "pu-239",
			CategoryID:       31,
		},
		{
			ID:               54,
			Name:             "U-235",
			Description:      "Уран.",
			MinSafetyClassID: 7,
			ItemName:         "1 кг",
			Price:            1_407_000,
			Slug:             "u-235",
			CategoryID:       31,
		},
		{
			ID:               55,
			Name:             "Азотная кислота",
			Description:      "Описание товара...",
			MinSafetyClassID: 1,
			ItemName:         "100 кг",
			Price:            6500,
			Slug:             "azot-kislota",
			CategoryID:       32,
		},
		{
			ID:               39,
			Name:             "Baker",
			Description:      "Мощность: 23 килотонны.",
			MinSafetyClassID: 7,
			ItemName:         "1 шт",
			Price:            1_222_190_000,
			Slug:             "baker",
			CategoryID:       23,
		},
		{
			ID:               40,
			Name:             "Trident II",
			Description:      "Мощность: 475 килотонны.",
			MinSafetyClassID: 7,
			ItemName:         "1 шт",
			Price:            2_528_740_000,
			Slug:             "tident-ii",
			CategoryID:       23,
		},
		{
			ID:               41,
			Name:             "Castle Yankee",
			Description:      "Мощность: 13,5 мегатонн.",
			MinSafetyClassID: 7,
			ItemName:         "1 шт",
			Price:            83_428_380_000,
			Slug:             "castle-yankee",
			CategoryID:       23,
		},
		{
			ID:               42,
			Name:             "Сибирская язва",
			Description:      "Летальность: 20%.",
			MinSafetyClassID: 7,
			ItemName:         "1 ампула",
			Price:            924_235_134,
			Slug:             "siberian-yazva",
			CategoryID:       24,
		},
		{
			ID:               43,
			Name:             "Эбола",
			Description:      "Летальность: 50%.",
			MinSafetyClassID: 7,
			ItemName:         "1 ампула",
			Price:            1_154_235_356,
			Slug:             "ebola",
			CategoryID:       24,
		},
		{
			ID:               44,
			Name:             "CNT65-12344-PE (Project genesys)",
			Description:      "Летальность: 99%.",
			MinSafetyClassID: 7,
			ItemName:         "1 ампула",
			Price:            21_642_246_384,
			Slug:             "cnt65-12344-pe",
			CategoryID:       24,
		},
	}, nil
}
