stages:
  - build
  - test
  - deploy

Build template:
  stage: build
  script:
    - cat index.tmpl | sed "s/COMMIT_HASH/$CI_COMMIT_SHORT_SHA/g" > index.html
  artifacts:
    paths:
      - ./index.html
    expire_in: 3h

Test Nginx configuration:
  stage: test
  needs:
    - job: Build template
  script:
    - sudo nginx -t -c $(pwd)/nginx.conf

Deploy:
  stage: deploy
  needs:
    - job: Build template
      artifacts: true
    - job: Test Nginx configuration
  script:
    - sudo scp $(pwd)/nginx.conf root@46.19.65.218:/etc/nginx/nginx.conf
    - sudo scp $(pwd)/index.html root@46.19.65.218:/var/www/html/index.html
    - sudo ssh root@46.19.65.218 systemctl restart nginx
  when: manual
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "develop")
