version: "3.9"

services:
  redis:
    image: "redis:alpine"
    container_name: redis_bamonka
    command: redis-server --requirepass passw0rd
    ports:
      - "26379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master