/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
 
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>

#include "bakery.h"

#define N 50 
 
int choosing[N] = { 0 }; 
int num[N] = { 0 }; 
int id = 0; 
int data = 'a'; 
 
struct queue_info_t 
{ 
	int id; 
	int num; 
}; 

void get_num(struct queue_info_t *info) 
{  
	sleep(rand() % 3); 

	while (choosing[id]); 

	choosing[id] = 1; 
	int i = id; 
	id++; 
	info->id = i; 
	int max = 0; 
	for (int j = 0; j < N; j++) 
		if (num[j] > max) 
		max = num[j]; 

	num[i] = max + 1; 
	info->num = num[i]; 
	choosing[i] = 0;  
}

int less(int a, int b, int c, int d) { 
	if (a < c)  
		return 1; 
	if (a > c) 
		return 0; 
	return b < d; 
} 
 
int get_data(struct queue_info_t *info) 
{ 
	sleep(rand() % 3); 

	int i = info->id; 
	for (int j = 0; j < N; j++) 
	{ 
		while (choosing[j]); 
		while (num[j] != 0 && less(num[j], j, num[i], i)); 
	} 
	int d = data; 
	data++; 
	num[i] = 0; 
	return d; 
} 

struct BAKERY *
bakery_proc_1_svc(struct BAKERY *argp, struct svc_req *rqstp)
{
	static struct BAKERY  result;
	struct queue_info_t info;

	switch (argp->op) 
	{ 
		case GET_NUM: 
		{ 
			get_num(&info); 
			result.id = info.id; 
			result.num = info.num; 
			break; 
		} 
		case GET_DATA: 
		{ 
			info.id = argp->id; 
			result.res = get_data(&info); 
			break; 
		} 
	}

	return &result;
}
