/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"errors"
	"net/http"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// CreateDepartment -
func (s *DefaultApiService) CreateDepartment(ctx context.Context, createDepartmentRequest CreateDepartmentRequest) (ImplResponse, error) {
	// TODO - update CreateDepartment with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Department{}) or use other options such as http.Ok ...
	//return Response(200, Department{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateDepartment method not implemented")
}

// CreateEmployee -
func (s *DefaultApiService) CreateEmployee(ctx context.Context, createEmployeeRequest CreateEmployeeRequest) (ImplResponse, error) {
	// TODO - update CreateEmployee with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Employee{}) or use other options such as http.Ok ...
	//return Response(200, Employee{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateEmployee method not implemented")
}

// CreateTeam -
func (s *DefaultApiService) CreateTeam(ctx context.Context, createTeamRequest CreateTeamRequest) (ImplResponse, error) {
	// TODO - update CreateTeam with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Team{}) or use other options such as http.Ok ...
	//return Response(200, Team{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateTeam method not implemented")
}

// CreateVacation -
func (s *DefaultApiService) CreateVacation(ctx context.Context, createVacationRequest CreateVacationRequest) (ImplResponse, error) {
	// TODO - update CreateVacation with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Vacation{}) or use other options such as http.Ok ...
	//return Response(200, Vacation{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateVacation method not implemented")
}

// DeleteDepartment -
func (s *DefaultApiService) DeleteDepartment(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update DeleteDepartment with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteDepartment method not implemented")
}

// DeleteEmployee -
func (s *DefaultApiService) DeleteEmployee(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update DeleteEmployee with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteEmployee method not implemented")
}

// DeleteTeam -
func (s *DefaultApiService) DeleteTeam(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update DeleteTeam with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("DeleteTeam method not implemented")
}

// FireEmployee -
func (s *DefaultApiService) FireEmployee(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update FireEmployee with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("FireEmployee method not implemented")
}

// GetDepartment -
func (s *DefaultApiService) GetDepartment(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetDepartment with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDepartment method not implemented")
}

// GetDepartmentBreadcrumbs -
func (s *DefaultApiService) GetDepartmentBreadcrumbs(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetDepartmentBreadcrumbs with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetDepartmentBreadcrumbsResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetDepartmentBreadcrumbsResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDepartmentBreadcrumbs method not implemented")
}

// GetDepartmentList -
func (s *DefaultApiService) GetDepartmentList(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetDepartmentList with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetDepartmentListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetDepartmentListResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDepartmentList method not implemented")
}

// GetEmployeeByDepartment -
func (s *DefaultApiService) GetEmployeeByDepartment(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetEmployeeByDepartment with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetEmployeeListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetEmployeeListResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEmployeeByDepartment method not implemented")
}

// GetEmployeeByID -
func (s *DefaultApiService) GetEmployeeByID(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetEmployeeByID with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Employee{}) or use other options such as http.Ok ...
	//return Response(200, Employee{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEmployeeByID method not implemented")
}

// GetEmployeeByNickname -
func (s *DefaultApiService) GetEmployeeByNickname(ctx context.Context, nickname string) (ImplResponse, error) {
	// TODO - update GetEmployeeByNickname with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Employee{}) or use other options such as http.Ok ...
	//return Response(200, Employee{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEmployeeByNickname method not implemented")
}

// GetEmployeeByTeam -
func (s *DefaultApiService) GetEmployeeByTeam(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetEmployeeByTeam with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetEmployeeListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetEmployeeListResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEmployeeByTeam method not implemented")
}

// GetEmployeeList -
func (s *DefaultApiService) GetEmployeeList(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetEmployeeList with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetEmployeeListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetEmployeeListResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetEmployeeList method not implemented")
}

// GetTeam -
func (s *DefaultApiService) GetTeam(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetTeam with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Team{}) or use other options such as http.Ok ...
	//return Response(200, Team{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTeam method not implemented")
}

// GetTeamList -
func (s *DefaultApiService) GetTeamList(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetTeamList with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetTeamListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetTeamListResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTeamList method not implemented")
}

// GetVacationList -
func (s *DefaultApiService) GetVacationList(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update GetVacationList with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, GetVacationListResponse{}) or use other options such as http.Ok ...
	//return Response(200, GetVacationListResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetVacationList method not implemented")
}

// IsSubscribed -
func (s *DefaultApiService) IsSubscribed(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update IsSubscribed with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, SubscribeResponse{}) or use other options such as http.Ok ...
	//return Response(200, SubscribeResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("IsSubscribed method not implemented")
}

// Login -
func (s *DefaultApiService) Login(ctx context.Context, loginRequest LoginRequest) (ImplResponse, error) {
	// TODO - update Login with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, LoginResponse{}) or use other options such as http.Ok ...
	//return Response(200, LoginResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Login method not implemented")
}

// MeGet -
func (s *DefaultApiService) MeGet(ctx context.Context) (ImplResponse, error) {
	// TODO - update MeGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Employee{}) or use other options such as http.Ok ...
	//return Response(200, Employee{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("MeGet method not implemented")
}

// Search -
func (s *DefaultApiService) Search(ctx context.Context, query string) (ImplResponse, error) {
	// TODO - update Search with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, SearchResponse{}) or use other options such as http.Ok ...
	//return Response(200, SearchResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Search method not implemented")
}

// Subscribe -
func (s *DefaultApiService) Subscribe(ctx context.Context, id string) (ImplResponse, error) {
	// TODO - update Subscribe with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, SubscribeResponse{}) or use other options such as http.Ok ...
	//return Response(200, SubscribeResponse{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Subscribe method not implemented")
}

// UpdateDepartment -
func (s *DefaultApiService) UpdateDepartment(ctx context.Context, id string, updateDepartmentRequest UpdateDepartmentRequest) (ImplResponse, error) {
	// TODO - update UpdateDepartment with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateDepartment method not implemented")
}

// UpdateEmployee -
func (s *DefaultApiService) UpdateEmployee(ctx context.Context, id string, body Employee) (ImplResponse, error) {
	// TODO - update UpdateEmployee with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateEmployee method not implemented")
}

// UpdateTeam -
func (s *DefaultApiService) UpdateTeam(ctx context.Context, id string, body Team) (ImplResponse, error) {
	// TODO - update UpdateTeam with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateTeam method not implemented")
}
