/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateEmployeeRequest struct {
	Password string `json:"password,omitempty"`

	Name string `json:"name,omitempty"`

	Nickname string `json:"nickname,omitempty"`

	DepartmentId string `json:"department_id,omitempty"`

	Position string `json:"position,omitempty"`

	Email string `json:"email,omitempty"`

	Phone string `json:"phone,omitempty"`

	BossId *string `json:"boss_id,omitempty"`

	Photo string `json:"photo,omitempty"`

	Level string `json:"level,omitempty"`

	Teams []TeamRole `json:"teams,omitempty"`
}

// AssertCreateEmployeeRequestRequired checks if the required fields are not zero-ed
func AssertCreateEmployeeRequestRequired(obj CreateEmployeeRequest) error {
	for _, el := range obj.Teams {
		if err := AssertTeamRoleRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseCreateEmployeeRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateEmployeeRequest (e.g. [][]CreateEmployeeRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateEmployeeRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateEmployeeRequest, ok := obj.(CreateEmployeeRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateEmployeeRequestRequired(aCreateEmployeeRequest)
	})
}
