/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UpdateDepartmentRequest struct {
	Name string `json:"name"`

	Description string `json:"description"`

	ParentId *string `json:"parent_id,omitempty"`
}

// AssertUpdateDepartmentRequestRequired checks if the required fields are not zero-ed
func AssertUpdateDepartmentRequestRequired(obj UpdateDepartmentRequest) error {
	elements := map[string]interface{}{
		"name":        obj.Name,
		"description": obj.Description,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseUpdateDepartmentRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UpdateDepartmentRequest (e.g. [][]UpdateDepartmentRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUpdateDepartmentRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUpdateDepartmentRequest, ok := obj.(UpdateDepartmentRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUpdateDepartmentRequestRequired(aUpdateDepartmentRequest)
	})
}
