/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetDepartmentBreadcrumbsResponse struct {
	List []DepartmentShort `json:"list,omitempty"`
}

// AssertGetDepartmentBreadcrumbsResponseRequired checks if the required fields are not zero-ed
func AssertGetDepartmentBreadcrumbsResponseRequired(obj GetDepartmentBreadcrumbsResponse) error {
	for _, el := range obj.List {
		if err := AssertDepartmentShortRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetDepartmentBreadcrumbsResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetDepartmentBreadcrumbsResponse (e.g. [][]GetDepartmentBreadcrumbsResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetDepartmentBreadcrumbsResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetDepartmentBreadcrumbsResponse, ok := obj.(GetDepartmentBreadcrumbsResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetDepartmentBreadcrumbsResponseRequired(aGetDepartmentBreadcrumbsResponse)
	})
}
