/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateTeamRequest struct {
	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`
}

// AssertCreateTeamRequestRequired checks if the required fields are not zero-ed
func AssertCreateTeamRequestRequired(obj CreateTeamRequest) error {
	return nil
}

// AssertRecurseCreateTeamRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateTeamRequest (e.g. [][]CreateTeamRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateTeamRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateTeamRequest, ok := obj.(CreateTeamRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateTeamRequestRequired(aCreateTeamRequest)
	})
}
