/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EmployeeShort struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Nickname string `json:"nickname,omitempty"`

	Working bool `json:"working,omitempty"`
}

// AssertEmployeeShortRequired checks if the required fields are not zero-ed
func AssertEmployeeShortRequired(obj EmployeeShort) error {
	return nil
}

// AssertRecurseEmployeeShortRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of EmployeeShort (e.g. [][]EmployeeShort), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseEmployeeShortRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aEmployeeShort, ok := obj.(EmployeeShort)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertEmployeeShortRequired(aEmployeeShort)
	})
}
