/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LoginRequest struct {
	Login string `json:"login,omitempty"`

	Password string `json:"password,omitempty"`
}

// AssertLoginRequestRequired checks if the required fields are not zero-ed
func AssertLoginRequestRequired(obj LoginRequest) error {
	return nil
}

// AssertRecurseLoginRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LoginRequest (e.g. [][]LoginRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLoginRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLoginRequest, ok := obj.(LoginRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLoginRequestRequired(aLoginRequest)
	})
}
