/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateVacationRequest struct {
	Start string `json:"start,omitempty"`

	End string `json:"end,omitempty"`

	Description string `json:"description,omitempty"`

	Id string `json:"id,omitempty"`
}

// AssertCreateVacationRequestRequired checks if the required fields are not zero-ed
func AssertCreateVacationRequestRequired(obj CreateVacationRequest) error {
	return nil
}

// AssertRecurseCreateVacationRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateVacationRequest (e.g. [][]CreateVacationRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateVacationRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateVacationRequest, ok := obj.(CreateVacationRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateVacationRequestRequired(aCreateVacationRequest)
	})
}
