/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Department struct {
	Id string `json:"id"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	ParentId *string `json:"parent_id,omitempty"`
}

// AssertDepartmentRequired checks if the required fields are not zero-ed
func AssertDepartmentRequired(obj Department) error {
	elements := map[string]interface{}{
		"id":   obj.Id,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDepartmentRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Department (e.g. [][]Department), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDepartmentRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDepartment, ok := obj.(Department)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDepartmentRequired(aDepartment)
	})
}
