/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DepartmentShort struct {
	Id string `json:"id"`

	Name string `json:"name"`
}

// AssertDepartmentShortRequired checks if the required fields are not zero-ed
func AssertDepartmentShortRequired(obj DepartmentShort) error {
	elements := map[string]interface{}{
		"id":   obj.Id,
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseDepartmentShortRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of DepartmentShort (e.g. [][]DepartmentShort), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseDepartmentShortRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aDepartmentShort, ok := obj.(DepartmentShort)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertDepartmentShortRequired(aDepartmentShort)
	})
}
