/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type CreateDepartmentRequest struct {
	Name string `json:"name"`

	Description string `json:"description"`

	ParentId *string `json:"parent_id,omitempty"`
}

// AssertCreateDepartmentRequestRequired checks if the required fields are not zero-ed
func AssertCreateDepartmentRequestRequired(obj CreateDepartmentRequest) error {
	elements := map[string]interface{}{
		"name":        obj.Name,
		"description": obj.Description,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseCreateDepartmentRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of CreateDepartmentRequest (e.g. [][]CreateDepartmentRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseCreateDepartmentRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aCreateDepartmentRequest, ok := obj.(CreateDepartmentRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertCreateDepartmentRequestRequired(aCreateDepartmentRequest)
	})
}
