/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Team struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Description string `json:"description,omitempty"`
}

// AssertTeamRequired checks if the required fields are not zero-ed
func AssertTeamRequired(obj Team) error {
	return nil
}

// AssertRecurseTeamRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Team (e.g. [][]Team), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTeamRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTeam, ok := obj.(Team)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTeamRequired(aTeam)
	})
}
