/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetTeamListResponse struct {
	List []Team `json:"list,omitempty"`
}

// AssertGetTeamListResponseRequired checks if the required fields are not zero-ed
func AssertGetTeamListResponseRequired(obj GetTeamListResponse) error {
	for _, el := range obj.List {
		if err := AssertTeamRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetTeamListResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetTeamListResponse (e.g. [][]GetTeamListResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetTeamListResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetTeamListResponse, ok := obj.(GetTeamListResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetTeamListResponseRequired(aGetTeamListResponse)
	})
}
