/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LoginResponse struct {
	Token string `json:"token,omitempty"`
}

// AssertLoginResponseRequired checks if the required fields are not zero-ed
func AssertLoginResponseRequired(obj LoginResponse) error {
	return nil
}

// AssertRecurseLoginResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of LoginResponse (e.g. [][]LoginResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseLoginResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aLoginResponse, ok := obj.(LoginResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertLoginResponseRequired(aLoginResponse)
	})
}
