/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type TeamShort struct {
	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}

// AssertTeamShortRequired checks if the required fields are not zero-ed
func AssertTeamShortRequired(obj TeamShort) error {
	return nil
}

// AssertRecurseTeamShortRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of TeamShort (e.g. [][]TeamShort), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseTeamShortRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aTeamShort, ok := obj.(TeamShort)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertTeamShortRequired(aTeamShort)
	})
}
