/*
 * balteca
 *
 * API for balteca
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type GetDepartmentListResponse struct {
	List []Department `json:"list,omitempty"`
}

// AssertGetDepartmentListResponseRequired checks if the required fields are not zero-ed
func AssertGetDepartmentListResponseRequired(obj GetDepartmentListResponse) error {
	for _, el := range obj.List {
		if err := AssertDepartmentRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseGetDepartmentListResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of GetDepartmentListResponse (e.g. [][]GetDepartmentListResponse), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseGetDepartmentListResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aGetDepartmentListResponse, ok := obj.(GetDepartmentListResponse)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertGetDepartmentListResponseRequired(aGetDepartmentListResponse)
	})
}
